services:
  - type: web
    name: sentiment-analysis-ml
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
